name: Workflow avec Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    

    - name: Création de l'artefact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path:  fichier.txt # Archive tout le répertoire de travail

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Téléchargement de l'artefact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact

    - name: Exécution des tests
      run: |
        # Exécutez vos tests sur l'application construite
        # Par exemple, exécutez les tests Jest, Mocha, etc.
        npm test
