name: Node.js Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node_version: [14.x, 16.x, 18.x] # Ajoutez ici les versions de Node.js que vous souhaitez tester
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install des dépendances
      run: npm install  # Ou yarn install, selon le gestionnaire de packages utilisé

    - name: Exécution des tests
      run: npm test  # Ou yarn test, selon le gestionnaire de packages utilisé
