name: Parallel Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node_version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install des dépendances
      run: npm install

    - name: Exécution des tests
      run: npm test
