name: Run Tests on Main Branch with Discord Notifications

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  notify_discord:
    name: Notify Discord
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Notify Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            Les tests sur la branche principale ont été exécutés avec succès.
            Résultat des tests: ${{ job.status }}
