name: Deploy Application

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Deploy to Cloud
        run: |
          echo "Deploying application using API_KEY: $API_KEY"
         
        env:
          API_KEY: ${{ secrets.API_KEY }}